#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 21 14:30:00 2022

@author: trotabas
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rc
import csv
from scipy.interpolate import interp1d
from scipy.integrate import odeint
import sys

#ion() # enables interactive mode
from mpl_toolkits.axes_grid1 import make_axes_locatable
from numpy import ma
from matplotlib import cm
import matplotlib.ticker as tick
import matplotlib.colors as colors
from numpy import loadtxt

df = pd.read_csv('NRLMSISE.txt', delim_whitespace=True)#, header=None)#, delimiter=None)

data_height  = np.array(df['Heit(km)'].tolist())       # km
data_density = 1e3*np.array(df['air(gm/cm3)'].tolist()) # kg/m3

# %%
#rho_f = interpolate.interp1d(data_height, data_density, kind='cubic')
rho_f = interp1d(data_height, data_density, kind='cubic')

# %%
x = np.linspace(100, 1000, 100001)

#fig, ax = plt.subplots(constrained_layout = False, figsize = (1.25*3.37,3))
fig, ax = plt.subplots( figsize = (1.25*3.37,3))
plt.gcf().subplots_adjust(right = 0.99, left = 0.15, wspace = 0.225, top = 0.99, hspace = 0.35, bottom = 0.15 )
ax.plot(x, rho_f(x), color = "crimson", label = r'$\textrm{NRLMSISE}$')
ax.set_xlabel(r'$\textrm{Altitude (km)}$')
ax.set_ylabel(r'$\textrm{mass density}$ $\mathrm{kg/m^{-3})}$')
ax.legend(loc=0, frameon = False)
ax.set_yscale('log')
plt.show()

#%%

np.savetxt("NRLMSISE_Mass_Density.txt", rho_f(x))
np.savetxt("NRLMSISE_Altitude.txt", x*1e3)

